# Generated by Django 3.1.4 on 2020-12-09 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201209_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='apodo',
            field=models.CharField(default='jorgoat', max_length=15),
        ),
    ]
